#!/bin/bash

# Développeur ....: K3rn€l_P4n1K
# Nom ............: zsh
# Description ....: Configuration personnelle de zsh
# Version ........: 1.0
# Date ...........: Fri Jul 29 21:31:48 CEST 2022
# Dépendances ....: zsh

# ------------------
# VARIABLES GLOBALES
# ------------------

# Chemin du script
SCRIPT="${0}"

# Nom du script
SCRIPT_NAME="$( basename ${0} )"

# Dossier du script
SCRIPT_DIR="$( dirname ${0} )"

# Fichier de log des erreurs
LOGERR="${SCRIPT_NAME}.err.log"

# ---------
# FONCTIONS
# ---------

# Exécutée lors de la sortie du script (CTRL+C par exemple)
onExit(){
    displayLog
}
trap onExit EXIT


# Exécutée lors d'une erreur
onError(){
    echo ".. ERR: dans le script ${SCRIPT_NAME}" >> ${LOGERR}
}
trap onError ERR

# Affiche les logs le cas échéant
displayLog(){
    if [ -s "${LOGERR}" ]; then
        echo ".. ERR: Sortie du script ${SCRIPT_NAME}"
        cat "${LOGERR}"
    fi
    rm -f "${LOGERR}"
}

# Vérifie si les fichiers en entrées sont des fichiers valide
checkFile(){
    file="${1}"
    if [ ! -s "${file}" ]; then
        echo "${file} n'existe pas" >> "${LOGERR}"
        exit 1
    fi
}

# vim et zsh
alias vim='nvim'
alias v='nvim'

# edition des dotfiles
alias rc='~/.dotfiles/install'
alias sz='source ~/.zshrc'

alias vv='v ~/.dotfiles/conf/vim'
alias vn='v ~/.dotfiles/conf/nvim'
alias vz='v ~/.dotfiles/conf/zsh; sz'

# docker
alias docker.arrete_tous_les_containers='docker container stop $(docker container ls -aq)'
alias docker.supprime_tous_les_containers='docker container rm $(docker container ls -q)'
alias docker.supprime_toutes_les_images='docker image rm $(docker image ls -q)'

alias docker.NETTOIE_TOUT='docker.arrete_tous_les_containers; docker.supprime_tous_les_containers; docker.supprime_toutes_les_images'

docker.status(){
    echo
    echo "volumes"
    docker volume ls
    echo
    echo "images"
    docker image ls
    echo
    echo "containers"
    docker container ls
}
